[tool.flake8]
ignore = ["D100", "D101", "D102", "D103"]
exclude = ['.eggs', '.git', '.tox', '.venv', '.build', 'report']
max-line-length = 88
max-complexity = 10

[tool.black]
line-length = 88
exclude = '''
/(
    | .eggs
    | .git
    | .tox
    | .venv
    | .build
    | report
)/
'''

[tool.isort]
profile = "black"
skip_glob = '''
/(
    | .eggs
    | .git
    | .tox
    | .venv
    | .build
    | report
)/
'''
