name: Release to Edge

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  check:
    uses: ./.github/workflows/check.yaml
    secrets: inherit


  release:
    needs: check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download the tested charms
        uses: actions/download-artifact@v4
        with:
          pattern: built_charms_*
          merge-multiple: true

      - name: List the names of the tested charms
        run: |
          echo "CHARM_NAMES=$(ls *.charm | paste -sd ,)" >> "$GITHUB_ENV"
          echo "${{ env.CHARM_NAMES }}"

      - name: Upload the tested charms to charmhub
        uses: canonical/charming-actions/upload-charm@2.7.0
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          built-charm-path: "${{ env.CHARM_NAMES }}"
